version: "3.7"

services:
  rnode:
    build:
        context: ./rnode
        target: prod
        # labels:
        #   - "com.ezuce.reach.git_commit=${GIT_COMMIT}"
    image: ${DKH_REPO}/rnode:${TAG}
    container_name: ${CONTAINER_NAME_PREFIX}rnode
    # ports:
    #   - 36015:36015/udp
    #   - 36015:36015/tcp
    #   - 46015:46015/udp
    #   - 46015:46015/tcp
    #   - 46014:46014/udp
    #   - 46014:46014/tcp
    #   - 36016:36016/udp
    #   - 36016:36016/tcp
    #   - 36025:36025/udp
    #   - 36025:36025/tcp
    #   - 5353:5353/tcp
    #   - 5354:5354/tcp
    #   - 3232:3232/tcp
    #   - 3233:3233/tcp
    #   - 3234:3234/tcp
    #   - 3235:3235/tcp
    #   - 3236:3236/tcp
    #   - 4238:4238/tcp
    #   - 3248:3248/tcp
    #   - 3247:3247/tcp
    ulimits:
      nproc: 50000

#TCP IN any 9090:9095
#UDP IN any 20000:57000
    network_mode: host
    # networks:
    #   1_vibesrv:
    #     aliases:
    #       - rnode
    # environment:
    #   - NETWORK=reach3
    #   - NODE=freeswitch@freeswitch.reach3${NETWORK_NAME_SUFFIX}
    #   - REACH_NODE=reach@reach.reach3${NETWORK_NAME_SUFFIX}
    #   - REACH_HOST=http://reach.reach3${NETWORK_NAME_SUFFIX}:8937
#    logging:
#      driver: none

#   reach:
#     image: ${DKH_REPO}/reach:${TAG}
#     container_name: ${CONTAINER_NAME_PREFIX}reach
#     networks:
#       1_reach3:
#         aliases:
#           - reach
#     volumes:
#       - db-reach:/home/user/reach/db-mnesia
#     environment:
#       - NETWORK=reach3${NETWORK_NAME_SUFFIX}
#       - REACH_NODE=reach@reach.reach3${NETWORK_NAME_SUFFIX}
#       - DOMAIN=${DOMAIN}
#       - NODE=reach@reach.reach3
#       - FSNODE=freeswitch@freeswitch.reach3${NETWORK_NAME_SUFFIX}
#       - KAMNODE=kamailio@kamailio.reach3${NETWORK_NAME_SUFFIX}

#   kamailio:
#     image: ${DKH_REPO}/kamailio:${TAG}
#     container_name: ${CONTAINER_NAME_PREFIX}kamailio
# #    entrypoint: /bin/bash
#     ports:
#       - 5060:5060/udp
#       - 5060:5060/tcp
#     networks:
#       0_sip_ext:
#         aliases:
#           - kamailio
#       1_reach3:
#         aliases:
#           - kamailio
#     environment:
#       - NETWORK=reach3
#       - REACH_NODE=reach@reach.reach3${NETWORK_NAME_SUFFIX}
#       - NAME=kamailio.reach3${NETWORK_NAME_SUFFIX}
#       - EXT_IP=${EXT_IP}
#       - HOST_IP=${HOST_IP}
#       - NODE=kamailio@kamailio.reach3${NETWORK_NAME_SUFFIX}

#   timescale:
#     image: ${DKH_REPO}/timescale:${TAG}
#     container_name: ${CONTAINER_NAME_PREFIX}timescale
#     networks:
#       1_reach3:
#         aliases:
#           - timescale
#     environment:
#       - NETWORK=reach3
#       - PASSWORD=reachpass
#     volumes:
#       - db-timescale:/var/lib/postgresql/data

#   frontend:
#     image: ${DKH_REPO}/frontend:${TAG}
#     container_name: ${CONTAINER_NAME_PREFIX}frontend
#     networks:
#       1_reach3:
#         aliases:
#           - frontend
#     environment:
#       - NETWORK=reach3
#       - DOMAIN=${DOMAIN}
#       - REACH_WS

#   ingress:
#     image: ${DKH_REPO}/ingress:${TAG}
#     container_name: ${CONTAINER_NAME_PREFIX}ingress
#     ports:
#       - 80:80
#       - 443:443
#       - 8080:8080
#     networks:
#       1_reach3:
#         aliases:
#           - ingress
#     environment:
#       - NETWORK=reach3${NETWORK_NAME_SUFFIX}
#       - DOMAIN=${DOMAIN}
#       - HTTPS_OPTION=${HTTPS_OPTION}
#       - LE_EMAIL=${LE_EMAIL}
#     volumes:
#       - ${PWD}/cert:/cert

#   rr:
#     image: ${DKH_REPO}/rr:${TAG}
#     container_name: ${CONTAINER_NAME_PREFIX}rr
#     networks:
#       1_reach3:
#         aliases:
#           - rr
#     environment:
#       - NODE=rr@rr.reach3
#     volumes:
#       - db-rr:/home/user/rr/data

# networks:
#   1_vibesrv:
#     driver: bridge
#     name: vibesrv${NETWORK_NAME_SUFFIX}
#   0_sip_ext:
#     driver: bridge
#     name: ext${NETWORK_NAME_SUFFIX}

# volumes:
#   db-timescale:
#     name: db-timescale.reach3${NETWORK_NAME_SUFFIX}
#   db-reach:
#     name: db-reach.reach3${NETWORK_NAME_SUFFIX}
#   db-rr:
#     name: db-rr.reach3${NETWORK_NAME_SUFFIX}
